### ISSUE TITLE
Attribution "OSM" un peu minimaliste

### ISSUE THREAD

**Issue by cquest** [incubateur-ademe/quefairedemesobjets#260]
Il serait préférable de mettre "OpenStreetMap" en toutes lettres avec un lien vers https://osm.org/copyright

https://github.com/incubateur-ademe/quefairedemesobjets/blob/9b3a5ddfed2cffc782bd02b8d7930b208369b3d0/static/to_compile/src/solution_map.ts#L52

**Comment by chrischarousset** [comment]
Fixed, merci !
<img width="77" alt="image" src="https://github.com/incubateur-ademe/quefairedemesobjets/assets/95855269/ebcbdc5c-395e-42c7-837e-2bdd097c1f88">
